### ISSUE TITLE
Error Generate Crud Foreign key Help

### ISSUE THREAD

**Issue by rodrigoselau** [dwijitsolutions/laraadmin#132]
> QueryException in Connection.php line 729:
> SQLSTATE[HY000]: General error: 1005 Can't create table `mkradius`.`#sql-6e0_67a` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `testes` add constraint `testes_pop_foreign` foreign key (`pop`) references `nas` (`id`))

This happened when I was generating a foreign key from an existing table ... any idea what happened?

**Comment by gdbhosale** [comment]
Hi,

This error occurs when Dropdown Migration is created after Your Migration.

e.g. Department Migration should be created before user module in order to assign department in user table.

Just change time in migration filename. You need to delete tables manually before migration to avoid migration not found error.

Best Regards,
