### ISSUE TITLE
Make Package 5.3 Supported - Work under Progress

### ISSUE THREAD

**Issue by gdbhosale** [dwijitsolutions/laraadmin#35]
We need so many changes including routes location and others.

https://laravel.com/docs/5.3/upgrade#5.2-deprecations

Please raise the issues if anything missing.

Regards,

**Comment by gdbhosale** [comment]
Entrust has problem over the 5.3. support.

https://github.com/Zizaco/entrust

Specially changes related to Blade Directives.

**Comment by pkumaravk** [comment]
Hi  Ganesh,
Just did a fresh install of laravel 5.3 and installed laraadmin as well.  its is giving errors wrt to blade directives probably related to entrust when i visit laradmin.dev/admin

Do you suggest running laraadmin over laravel 5.2 ?

**Comment by slozano95** [comment]
@pkumaravk actually LaraAdmin is only supported on 5.2, we are working on 5.3 
@gdbhosale blade directives can be managed by using a double parenthesis like `@role(("SUPER_ADMIN"))`

I will use this "fix" until entrust is updated

**Comment by pkumaravk** [comment]
yup .. just installed over laravel 5.2 and seems to working ok.  

you need to mention the laravel 5.2 requirement (not working with laravel 5.3) in the install instructions till you fix this.  

laraadmin looks great.. will check it out and revert back to you.  if you need any assist with porting this to laravel 5.3 give a shout.  glad to help

**Comment by gdbhosale** [comment]
Hello @pkumaravk @slozano95 ,

Entrust blade issue has been resolved.
In LAProvider:


```
if(LAHelper::laravel_ver() == 5.3) {
    // Call to Entrust::hasRole
    Blade::directive('role', function($expression) {
        return "<?php if (\\Entrust::hasRole({$expression})) : ?>";
    });
    
    // Call to Entrust::can
    Blade::directive('permission', function($expression) {
        return "<?php if (\\Entrust::can({$expression})) : ?>";
    });
    
    // Call to Entrust::ability
    Blade::directive('ability', function($expression) {
        return "<?php if (\\Entrust::ability({$expression})) : ?>";
    });
}
```
Please report more issues if found :+1:

**Comment by gdbhosale** [comment]
Routes related issues in 5.3 has been fixed.

We don't have access to Auth Middle-ware in Controller __construct for 5.3. So

```
        // Field Access of Listing Columns
		if(\Dwij\Laraadmin\Helpers\LAHelper::laravel_ver() == 5.3) {
			$this->middleware(function ($request, $next) {
				$this->listing_cols = ModuleFields::listingColumnAccessScan('Departments', $this->listing_cols);
				return $next($request);
			});
		} else {
			$this->listing_cols = ModuleFields::listingColumnAccessScan('Departments', $this->listing_cols);
		}
```
There are more changes in Admin Routes:
```
$as = "";
if(\Dwij\Laraadmin\Helpers\LAHelper::laravel_ver() == 5.3) {
	$as = config('laraadmin.adminRoute').'.';
	
	// Routes for Laravel 5.3
	Route::get('/logout', 'Auth\LoginController@logout');
}

Route::group(['as' => $as, 'middleware' => ['auth', 'permission:ADMIN_PANEL']], function () {
```

Please check the latest commits.

**Comment by gdbhosale** [comment]
Tested on 5.3. Working well. Closing issue

**Comment by Ethosteck** [comment]
Hi Ganesh,
After searching a lot i landed on this page.
I am Using 5.3 but user with another role is unable to access the dashboard. Kindly help as i have been working with branch only. i have trying since many days to resolve the matter but unable to do so.  Kindly Help. Awaiting Reply in anticipation.
@gdbhosale 

![screen shot 2018-02-16 at 21 15 27](https://user-images.githubusercontent.com/10820178/36315908-e12cf276-135e-11e8-9ea1-03bbb1a30ada.png)
![screen shot 2018-02-16 at 21 16 46](https://user-images.githubusercontent.com/10820178/36315909-e15d2842-135e-11e8-8dcc-50ecc4ae26d8.png)

**Comment by Ethosteck** [comment]
Hey  Ganesh and All team,

Really thanks for guiding me to right direction i didn't say that  i have solve the problem for now but i did to make my project running. 
Information for other users who would be facing same issue as mine.

Steps 
1.) Don't change laraadmin admin default module after installation. which i have done in employes and users although restore doesn't help.
2.) if you want to change anything do it before installation in vendor/dwij/laraadmin and install it.
3.) create project laravel 5.4 
4.) added the cloned repo of dwij/laraadmin under vendor
5.) add following in vendor/composer/autoload_psr4.php if not der
    5.1 'Dwij\\Laraadmin\\' => array($vendorDir . '/dwij/laraadmin/src'),
    5.2 'Zizaco\\Entrust\\' => array($vendorDir . '/zizaco/entrust/src/Entrust'),
    5.3 'Yajra\\Datatables\\' => array($vendorDir . '/yajra/laravel-datatables-oracle/src'),
    5.4 'Spatie\\DbDumper\\' => array($vendorDir . '/spatie/db-dumper/src'),
    5.5  'Spatie\\Backup\\' => array($vendorDir . '/spatie/laravel-backup/src'),
6.) composer dump autoload
7.) give necessary permission 
 chmod -R 777 storage/ bootstrap/ vendor/ database/migrations/ routes/ app/Http/Controllers/ resources/ app/
8.) run php artisan la:install

Every thing will be fine up and running.

I am still comparing these two codes what went wrong actually so that it can removed permanently from this wonderful package. 

Really Appreciate all your effort guys Ganesh and All team Thanks.

 @gdbhosale
