### ISSUE TITLE
Change font icon for the menus

### ISSUE THREAD

**Issue by willmkt** [dwijitsolutions/laraadmin#81]
Hi, how can i change the font icon for the menus?

I realy like http://themes-pixeden.com/font-demos/7-stroke/

Thanks.

**Comment by slozano95** [comment]
Hi @willmkt you should be able to change it using the blade files to include required files
But have in mind LaraAdmin project use FontAwesome to manage icons so module creation and so many features use this icons, please check the structure of how modules are taken from db to change the appropiate files on modules creation because menu icons are part of modules table in db

Best regards

**Comment by gdbhosale** [comment]
Hi,

You can now extend this package to have your own theme + logic.

Check http://laraadmin.com/docs/1.0/extending

Closing the issue.
