### ISSUE TITLE
[help] can't run application

### ISSUE THREAD

**Issue by tinggalklik** [dwijitsolutions/laraadmin#87]
I have installed **laraadmin** however, as there is a bit of a problem, due to lack of my knowledgement about programming, I hope you are all willing to help me, thank in advance 

`Fatal error: Class 'Illuminate\Foundation\Application' not found in D:\xampp\htdocs\laraadmin\bootstrap\app.php on line 14`

```
*/

$app = new Illuminate\Foundation\Application(
    realpath(__DIR__.'/../')
);

/*
```

Regards

**Comment by slozano95** [comment]
@tinggalklik Hi friend, LaraAdmin is an admin panel based on Laravel, you should first check laravel installation and using composer to include packages because I see in your "D:\xampp\htdocs\laraadmin\bootstrap\app.php on line 14" that maybe you just clone the repo, it doesn't work like that, you shoudl first Install laravel and then follow steps on laraadmin.com

Best Regards

**Comment by tinggalklik** [comment]
Thanks Mr @slozano95 for quick reply.....
I tried cloning the repo, but then I rearrange folders manually, because I think it doesn't comply with that orders...
but I think nothing has changed about concerning the composition of the structure...
but I'm very impressed to follow your suggestions

**Comment by gdbhosale** [comment]
Hello @tinggalklik

You can go ahead by changing the laravel structure and using laraadmin.
You will need to fork the laraadmin from github and add into your project directly.
Follow this document https://getcomposer.org/doc/05-repositories.md#vcs

Regards,

**Comment by tinggalklik** [comment]
Thank you for the advice
and you have been willing to help me 
now laraadmin running well for me (y)
